"""Generate the licensed synthetic healthy and faulty example recordings."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from signal_processing_toolkit.demo import ExperimentConfig, SimulatedMaintenanceSource


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=Path("recordings"))
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    for faulty, name in ((False, "healthy"), (True, "faulty")):
        config = ExperimentConfig(faulty=faulty, seed=7)
        samples = np.concatenate(
            [chunk.samples for chunk in SimulatedMaintenanceSource(config).chunks()]
        )
        np.savez_compressed(
            args.output / f"{name}.npz",
            samples=samples,
            sampling_rate=config.sampling_rate,
            license="MIT; synthetic data generated by SignalProcessingToolkit",
        )
        print(args.output / f"{name}.npz")


if __name__ == "__main__":
    main()
